/**
 * Bundles the Material Symbols this package actually draws.
 *
 * `@iconify/react` fetches an icon from Iconify's API the first time it is
 * asked for one it does not know, so a toolbox renders its buttons empty and
 * fills them in a network round trip later. Registering the icon data up
 * front removes both the wait and the request -- which the offline painter
 * bundle has no way to make in the first place.
 *
 * The whole collection is 7MB, so this walks the sources for the names in use
 * and writes only those into `src/components/materialSymbols.ts`. Run
 * `pnpm run build:icons` after adding an icon; `materialSymbols.test.ts`
 * fails if a name is referenced without being bundled.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const packageRoot = resolve(import.meta.dirname, "..");
const repoRoot = resolve(packageRoot, "..");
const output = join(packageRoot, "src/components/materialSymbols.ts");

/** Every `.ts`/`.tsx` file under the directories the applications are built from. */
function sourceFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) {
      return entry.name === "node_modules" || entry.name.startsWith("dist")
        ? []
        : sourceFiles(path);
    }
    return /\.tsx?$/.test(entry.name) && path !== output ? [path] : [];
  });
}

const used = new Set<string>();
for (const file of [join(packageRoot, "src"), join(repoRoot, "frontend")].flatMap(
  sourceFiles,
)) {
  for (const [, name] of readFileSync(file, "utf8").matchAll(
    /material-symbols:([a-z0-9-]+)/g,
  )) {
    used.add(name);
  }
}

interface IconifyCollection {
  width: number;
  height: number;
  icons: Record<string, { body: string; width?: number; height?: number }>;
  aliases?: Record<string, { parent: string }>;
}

const collection: IconifyCollection = JSON.parse(
  readFileSync(
    join(packageRoot, "node_modules/@iconify-json/material-symbols/icons.json"),
    "utf8",
  ),
);

const bundled = [...used].sort().map((name) => {
  // An alias is a second name for an icon rather than a body of its own, so
  // follow it to the icon it renames and bundle that under the name in use.
  const resolved = collection.aliases?.[name]?.parent ?? name;
  const icon = collection.icons[resolved];
  if (!icon) throw new Error(`material-symbols:${name} is not in the collection`);
  return `    ${JSON.stringify(name)}: ${JSON.stringify(icon)},`;
});

writeFileSync(
  output,
  `/**
 * The Material Symbols the painter and its hosts draw, as icon data.
 *
 * Generated by \`scripts/buildIconCollection.ts\` from
 * \`@iconify-json/material-symbols\`; run \`pnpm run build:icons\` rather than
 * editing this file. \`./Icon\` registers it, which is what makes an icon
 * paint with the frame that asks for it instead of after a fetch.
 */
export const materialSymbols = {
  prefix: "material-symbols",
  width: ${collection.width},
  height: ${collection.height},
  icons: {
${bundled.join("\n")}
  },
};
`,
);

console.log(`Bundled ${bundled.length} icons into ${output}`);
