env = "dev"
base_url = "http://localhost:3000"

db_url = "postgres://"
db_max_connections = 5
db_acquire_timeout = 3

official_account_login_name = ""

aws_access_key_id = "aws_access_key_id"
aws_secret_access_key = "aws_secret_access_key"
aws_region = "aws_region"
aws_s3_bucket = "aws_s3_bucket"
r2_endpoint_url = "r2_endpoint_url"
r2_public_endpoint_url = "r2_public_endpoint_url"

smtp_host = ""
smtp_port = 587
smtp_user = ""
smtp_password = ""
email_from_address = ""
