name: main
on:
  push:
    branches:
      - main

jobs:
  image:
    permissions:
      contents: read
      packages: write
      attestations: write
    runs-on: ubuntu-24.04-arm
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: oeee_cafe
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install SQLx CLI
        run: cargo install sqlx-cli --no-default-features --features postgres
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
      - name: Run migrations
        run: sqlx migrate run
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/oeee_cafe
      - name: Generate SQLx metadata
        run: cargo sqlx prepare
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/oeee_cafe
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - id: arch
        run: echo arch=arm64 >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@v6
        with:
          context: .
          pull: "true"
          push: "true"
          no-cache: "false"
          build-args: GIT_COMMIT=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository }}:git-${{ github.sha }}-${{ steps.arch.outputs.arch }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
          annotations: |
            org.opencontainers.image.title=OEEE Cafe
            org.opencontainers.image.description=OEEE Cafe
            org.opencontainers.image.url=https://oeee.cafe/
            org.opencontainers.image.source=https://github.com/yangnaru/oeee-cafe
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=AGPL-3.0-only
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}:build-cache-${{ steps.arch.outputs.arch }}
            type=registry,ref=ghcr.io/${{ github.repository }}:sccache-${{ steps.arch.outputs.arch }}
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository }}:build-cache-${{ steps.arch.outputs.arch }},mode=max
            type=registry,ref=ghcr.io/${{ github.repository }}:sccache-${{ steps.arch.outputs.arch }},mode=max
          provenance: false
